Este profile configura Tikiwiki para trabajar en ALMA.

Crea también los profiles necesarios para crear asignaturas de manera automática.

Se puede ejecutar directamente en Admin > Profiles > Advanced > Profile Tester

Esta sección se encarga de configurar las opciones generales de Tiki. ¡No olvides cambiar el password del correo por el password original!

Tampoco olvides copiar el contenido de Crear_Comunidad_de_Practica_Template a la página wiki con el mismo nombre!

{CODE(caption="YAML" wrap="1")}
preferences:
  language: es
  feature_wysiwyg:  y
  wysiwyg_default: y
  wysiwyg_optional: y
  wikiplugin_equation: y
  wikiplugin_perspective: n
  wikiplugininline_perspective: n
  wikiplugininline_equation: y
  feature_blogs:  n
  feature_categories:  y
  feature_file_galleries:  n
  feature_forums:  n
  feature_freetags:  n
  feature_help:  n
  feature_trackers:  n
  feature_mytiki:  y
  feature_userPreferences:  y
  feature_profiles: y
  feature_perspective: y
  allowRegister:  y
  min_username_length:  1
  max_username_length:  50
  min_pass_length:  4  
  forgotPass:  y
  cookie_name:  ALMA
  wikiHomePage:  HomePage
  sender_email:  alma@uah.es
  siteTitle:  ALMA
  browsertitle: ALMA
  site_title_location: before
  server_timezone: Madrid/Europe
  display_timezone: Madrid/Europe
  zend_mail_handler: smtp
  default_mail_charset: utf-8
  zend_mail_smtp_user: alma.disciplinar@gmail.com
  zend_mail_smtp_pass: password
  zend_mail_smtp_port: 465
  zend_mail_smtp_security: ssl
  zend_mail_smtp_auth: plain
  zend_mail_smtp_server: smtp.gmail.com
  log_mail: n
  wikiplugin_datachannel: y
  profile_channels: crear_comunidad, tiki://local, Crear_Comunidad_de_Practica_Template, Admins
  sitelogo_title: ALMA (Aula Libre Multidisciplinar Abierta)
  sitelogo_src: img/tiki/tikisitelogo.png
  sitelogo_alt: Alma
{CODE}

Esta sección se encarga de crear las páginas Wiki con el profile de Crear Comunidad de Paractica y su Data Channel correspondiente. Los asigna al grupo de Profiles y sólo los admins son capaces de ejecutar y ver esas páginas.

{CODE(caption="YAML" wrap="1")}
objects:
  -
    type: wiki_page
    ref: wiki1
    data:
      name: Crear_Comunidad_de_Practica_GUI
      content: "{DATACHANNEL(channel=crear_comunidad)}nombre_asignatura, Nombre de la comunidad de practica{DATACHANNEL}"
  -
    type: wiki_page
    ref: wiki2
    data:
      name: Crear_Comunidad_de_Practica_Template
      content: Rellenar el contenido de esta pagina con el archivo del mismo nombre
  -
    type: category
    ref: profilecateg
    data:
      name: Profiles
      description: Categoria donde se almacenan los profiles de las comunidades de practica
      items:
       - [ wiki_page, $wiki1 ]
       - [ wiki_page, $wiki2 ]
permissions:
 Admins:
  objects:
   -
    type: category
    id: $profilecateg
    allow:
      - admin
 Registered:
  objects:
   -
    type: category
    id: $profilecateg
    deny: view, edit, view_category, edit_category
 Anonymous:
  objects:
   -
    type: category
    id: $profilecateg
    deny: view, edit, view_category, edit_category
{CODE}

Creamos el menú que permite cambiar de asignatura a los usuarios que estén registrados en la plataforma

{CODE(caption="YAML", wrap="1")}
objects:
 -
  type: module
  ref: switcher
  data:
   name: perspective
   position: left
   order: 10
   groups: [ Registered ]
   params:
     title: Asignaturas
{CODE}